name: paperpod
description: A text-to-speech podcast app

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3
  
  # State Management
  provider: ^6.0.5
  flutter_riverpod: ^2.0.0
  
  # UI
  cupertino_icons: ^1.0.0
  google_fonts: ^6.2.1
  
  # Features
  share_plus: ^10.1.4  # or the latest version
  flutter_tts: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 